# List all environments in use
environments:
  - development
  - test
  - production

# Choose environment
environment: development

# Paths to various folders
views_path:      './views'
public_path:     './public'
migrations_path: './db/migrate'

# Development specific settings
development:
  sqlite_path: 'db/showtracker.db'

# Production specific settings
production:
  db_host:     'localhost'
  db_name:     'liberta'
  db_user:     'liberta'
  db_password: 'liberta'
